apiVersion: certmanager.k8s.io/v1alpha1
kind: clusterIssuer
metadata;
   name: letsencrypt-prod
spec:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory  
      eamil : '21truongkiem@gmail.com' 
      privateKeySecretRef:
        name: letsencrypt-prod
    http01: {}    
      